### ISSUE TITLE
How DIP_INFRA_POSTGRES_IMAGE_TAG is provided?

### ISSUE THREAD

**Issue by nilcolor** [bibendi/dip-postgres#1]
There is the `DIP_INFRA_POSTGRES_IMAGE_TAG` env that represents PG version. But it is not clear how to provide a value for this one. Is it provided from the main `dip` setup via 

```
environment:
  DIP_INFRA_POSTGRES_IMAGE_TAG: 12
```
(this way it is still yields "WARN[0000] The "DIP_INFRA_POSTGRES_IMAGE_TAG" variable is not set. Defaulting to a blank string.")
Or there is another way?

**Comment by bibendi** [comment]
You should not touch `DIP_INFRA_POSTGRES_IMAGE_TAG` in your dip.yml.

If you want to use a specific version of Postgres, you can use the following code in your dip.yml

```yaml
infra:
  postgres:
    git: https://github.com/bibendi/dip-postgres.git
    ref: v15
```

https://github.com/bibendi/dip-postgres/blob/v15/.env
https://github.com/bibendi/dip?tab=readme-ov-file#dip-infra
